# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GPUImageDemo
	pod 'GPUImage'
    pod 'Masonry'
    pod 'TZImagePickerController'
    pod 'TYCyclePagerView'
#    pod 'libx265', '~> 3.0'
#    pod 'librtmp-iOS', '~> 1.1.0'
  pod 'libyuv-iOS', '~> 1.0.2'
#  pod 'libx264-iOS'
end
